export const sectionMusicScenes = {
  home: {
    label: 'Waking Home',
    direction: 'Slow waking ambient music with soft glassy synths, gentle rolling percussion, and a warm, peaceful startup feeling.',
    keywords: ['waking', 'soft synth', 'rolling', 'peaceful', 'dreamlike'],
    audioStemFolder: '/audio/home/',
    intensity: 0.25,
    tempo: 70,
    texture: 'soft glass',
  },
  studio: {
    label: 'Studio Premise',
    direction: 'Calm creative studio atmosphere with warm room tone, quiet concentration, glass harmonics, and precise product development.',
    keywords: ['studio', 'calm', 'precision', 'warm', 'focus'],
    audioStemFolder: '/audio/studio/',
    intensity: 0.32,
    tempo: 72,
    texture: 'warm room',
  },
  solLamp: {
    label: 'SOL Lamp',
    direction: 'Warm modular lighting atmosphere with glowing synth pads, soft electronic pulses, and a calm premium product energy.',
    keywords: ['glowing', 'modular', 'warm', 'premium', 'future'],
    audioStemFolder: '/audio/sol-lamp/',
    intensity: 0.4,
    tempo: 78,
    texture: 'warm synth',
  },
  solX: {
    label: 'SOL X Lamp',
    direction: 'Refined additive manufactured lamp atmosphere with clean circular forms, luminous pads, and gentle kinetic pulses.',
    keywords: ['additive', 'luminous', 'precise', 'kinetic', 'clean'],
    audioStemFolder: '/audio/sol-x/',
    intensity: 0.42,
    tempo: 80,
    texture: 'luminous pulse',
  },
  plastivista: {
    label: 'PlastiVista',
    direction: 'Organic circular economy soundscape with gentle mechanical textures, recycled material rhythm, and creative workshop energy.',
    keywords: ['organic', 'recycled', 'mechanical', 'optimistic', 'earthy'],
    audioStemFolder: '/audio/plastivista/',
    intensity: 0.5,
    tempo: 82,
    texture: 'organic mechanical',
  },
  revoChair: {
    label: 'Revo Chair',
    direction: 'Quiet furniture studio ambience with smooth rotational motion and sculptural wood and polymer warmth.',
    keywords: ['furniture', 'rotational', 'sculptural', 'grounded', 'warm'],
    audioStemFolder: '/audio/revo-chair/',
    intensity: 0.36,
    tempo: 74,
    texture: 'soft furniture',
  },
  solWheel: {
    label: 'Sol Wheel',
    direction: 'Playful product research ambience with small rolling gestures, soft tactile clicks, and gentle discovery.',
    keywords: ['rolling', 'tactile', 'playful', 'research', 'motion'],
    audioStemFolder: '/audio/sol-wheel/',
    intensity: 0.34,
    tempo: 76,
    texture: 'rolling tactile',
  },
  process: {
    label: 'Process',
    direction: 'Quiet prototyping studio ambience with soft machine clicks, subtle workshop rhythm, and focused creative energy.',
    keywords: ['prototype', 'studio', 'machine', 'focused', 'calm'],
    audioStemFolder: '/audio/process/',
    intensity: 0.35,
    tempo: 75,
    texture: 'workshop ambient',
  },
  dram: {
    label: 'DRAM System',
    direction: 'Distributed manufacturing network ambience with synchronized pulses, clean system logic, and calm future infrastructure.',
    keywords: ['distributed', 'network', 'system', 'local', 'future'],
    audioStemFolder: '/audio/dram/',
    intensity: 0.46,
    tempo: 84,
    texture: 'network pulse',
  },
  capabilities: {
    label: 'Capabilities',
    direction: 'Elegant capability reel music with precise transitions, confident movement, and refined design studio momentum.',
    keywords: ['capabilities', 'confident', 'minimal', 'transition', 'design'],
    audioStemFolder: '/audio/capabilities/',
    intensity: 0.38,
    tempo: 79,
    texture: 'refined motion',
  },
  icff: {
    label: 'ICFF Exhibition',
    direction: 'Elegant gallery ambience with premium design fair atmosphere, soft movement, and polished calm.',
    keywords: ['gallery', 'premium', 'design fair', 'cinematic', 'calm'],
    audioStemFolder: '/audio/icff/',
    intensity: 0.45,
    tempo: 80,
    texture: 'gallery ambient',
  },
  contact: {
    label: 'Next System',
    direction: 'Slow closing ambience with warm invitation, soft glass chimes, and a spacious premium finish.',
    keywords: ['closing', 'invitation', 'glass', 'optimistic', 'spacious'],
    audioStemFolder: '/audio/contact/',
    intensity: 0.28,
    tempo: 68,
    texture: 'soft close',
  },
};
