export const legacyRouteMap = {
  '/category/all-products': '/shop/original-sol',
  '/category/combos': '/shop/original-sol',
  '/category/s0-shades': '/shop/original-sol',
  '/category/furniture': '/gallery',
  '/product-page/s01': '/product/s01',
  '/product-page/s02': '/product/s02',
  '/product-page/s03': '/product/s03',
  '/product-page/s04': '/product/s04',
  '/product-page/s01-shade': '/product/s01-shade',
  '/product-page/s02-shade': '/product/s02-shade',
  '/product-page/s03-shade': '/product/s03-shade',
  '/product-page/s04-shade': '/product/s04-shade',
  '/product-page/s0l-planter': '/product/s0l-planter',
  '/product-page/s0-combo': '/product/s0l-combo',
  '/product-page/s0l-combo': '/product/s0l-combo',
  '/product-page/s0l-base': '/product/s0l-base',
  '/product-page/s0l-divider': '/product/s0l-divider',
  '/product-page/s0l-accessory-kit': '/product/s0l-accessory-kit',
  '/product-page/s0l-magnetic-clip': '/product/s0l-magnetic-clip',
  '/s01': '/product/s01',
  '/r-d': '/plastivista',
  '/sol-figurines-page': '/gallery',
  '/revo-page': '/gallery',
  '/portfolio/landscape-magazine': '/gallery',
  '/portfolio/wild-spirit': '/gallery',
  '/portfolio/espinas-mezcal-ad': '/gallery',
  '/portfolio/summer-secrets': '/gallery',
  '/portfolio/under-the-sun': '/gallery',
  '/portfolio/may-28th': '/gallery',
  '/english-refund-policy': '/contact',
  '/english-terms-conditions': '/contact',
  '/accessibility-statement': '/contact',
  '/english-shipping-policy': '/contact',
  '/english-privacy-policy': '/contact',
};

export const resolveLegacyRoute = (routePath) => legacyRouteMap[routePath] ?? routePath;
